
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 140
#define YY_END_OF_BUFFER 141
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[440] =
    {   0,
        0,    0,  141,  140,    3,    2,    1,   29,  140,   41,
       49,  140,   18,   19,   39,   37,   27,   38,   28,   40,
      124,  124,   33,   26,   24,    6,   25,   32,   55,  138,
       22,   23,   31,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,   20,   50,   21,   30,   48,    0,  135,
        9,   51,   15,    0,    0,    7,   35,   10,   36,   11,
       53,    0,  132,    0,    4,    8,  131,    0,    0,  139,
      139,  139,  127,  124,  139,    0,  124,  124,  124,   34,
       42,   45,   54,   47,   46,   43,  138,   16,  138,  138,

      138,  138,  138,  138,  138,  138,  138,  138,   74,  138,
      138,  138,  138,  138,  138,  138,  138,   80,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  115,
      138,  138,  138,  138,  138,  138,  138,   17,   52,  136,
      136,   56,  132,    0,  129,    0,    0,    4,  131,  131,
        0,  128,  125,  125,    0,    0,  133,    0,  139,  124,
      124,  124,   12,   13,   44,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,   73,  138,  138,  138,   87,  138,

      138,  138,   58,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,   63,  138,   57,  138,  138,
      138,  138,  138,    0,  132,    5,    0,  131,  125,  125,
      126,  133,  130,  123,  123,  124,  124,  124,  124,   14,
      138,  138,  138,  138,   82,   79,  138,   84,  138,  138,
      138,  138,  138,   81,  122,  138,  138,  138,  138,  138,
       91,  138,  138,  138,  138,   88,  138,  138,    0,  137,
      118,  138,  138,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,  138,  138,  138,  138,   62,  138,  138,

      134,  112,   61,  138,  138,  111,  138,  125,  126,  123,
      123,  138,  138,  138,   72,   66,   60,   90,  138,  138,
      138,  138,  138,   99,   86,  138,  138,  138,  138,  138,
      138,    0,  113,  138,  138,  138,  138,  138,  138,  138,
      138,  138,  138,   89,  138,  138,   59,  138,  138,   68,
      138,  138,   75,   71,  138,   77,  138,  138,  138,   85,
      138,  138,  138,  138,  120,  138,  138,  119,  106,    0,
      138,  138,  138,  138,  138,   94,  114,  138,   69,  102,
       97,  138,   78,  138,  105,  138,  138,  138,   83,  138,
       76,  116,  101,   65,  138,  138,  138,    0,  121,  100,

       95,  138,  138,  138,  138,  138,  138,  138,  138,   92,
       70,  138,  138,  138,    0,  138,  110,  117,   98,  138,
      138,  138,  108,  138,  138,   96,    0,   93,  138,  107,
      138,  109,   64,  103,  138,  104,  138,   67,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,   22,   23,   24,
       25,   26,   27,   28,   29,   30,   29,   31,   32,   33,
       34,   34,   34,   34,   34,   35,   34,   34,   34,   34,
       34,   34,   34,   34,   34,   34,   34,   36,   34,   34,
       37,    1,   38,   39,   40,    1,   41,   42,   43,   44,

       45,   46,   47,   48,   49,   34,   50,   51,   52,   53,
       54,   55,   56,   57,   58,   59,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[70] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    1,    4,    4,    4,
        4,    1,    1,    1,    1,    1,    1,    1,    4,    4,
        4,    4,    4,    5,    5,    5,    1,    1,    1,    4,
        4,    4,    4,    4,    4,    4,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    1,    1,    1,    1
    } ;

static const flex_int16_t yy_base[447] =
    {   0,
        0,    0,  704,  705,  705,  705,  705,  678,  696,  676,
       62,  693,  705,  705,  674,   58,  705,   59,   57,   69,
       79,  131,  676,  705,   64,  672,   54,  705,  705,    0,
      705,  705,  671,   49,   39,   65,   47,   57,   77,  641,
       81,  640,  639,   94,  637,   96,  646,  125,   75,  632,
       63,   97,  640,  705,  111,  705,  705,  705,  682,  705,
      705,  705,  705,  678,  677,  705,  705,  705,  705,  705,
      705,  669,  172,  672,    0,  705,  176,  194,  139,  212,
      225,  234,  240,  246,  252,  180,  268,  258,  286,  705,
      658,  705,  705,  705,  705,  135,    0,  705,  624,  623,

      626,  634,  619,  116,  636,  635,  622,  628,  613,  614,
      611,  147,  619,  616,  614,  610,  607,    0,  610,  122,
      611,  619,  603,  599,  607,  608,  613,  614,  599,  113,
      613,  192,  613,  599,   81,  597,  602,  597,  162,    0,
      249,  604,  591,  137,  598,  587,  600,  705,  705,  705,
      705,  705,  705,  297,  705,  632,  212,    0,  309,  705,
      330,  705,  240,  338,  282,  313,  344,    0,  373,  348,
      361,  389,  705,  705,  618,  583,  596,  589,  598,  593,
      592,  593,  578,  576,  178,  592,  590,  586,  578,  575,
      583,  569,  585,  584,    0,  570,   51,  564,  577,  574,

      560,  570,    0,  603,  566,  563,  565,  562,  552,  164,
      561,  557,  550,  549,  557,  550,  547,  556,  559,  544,
      559,  543,  546,  546,  553,    0,  539,    0,  552,  554,
      543,  545,  541,  366,  402,  579,  407,  418,  434,  423,
      426,  705,  705,  285,  288,  705,  449,  705,  460,  705,
      533,  532,  543,  537,    0,    0,  538,    0,  527,  525,
      534,  522,  530,    0,    0,  523,  526,  533,  526,  517,
        0,  530,  517,  532,  515,    0,  520,  509,  511,    0,
      510,  526,  517,  524,  519,  514,  513,  504,  511,  502,
      513,  498,  507,  512,  497,  510,  504,    0,  489,  492,

        0,    0,    0,  490,  503,    0,  503,  705,  705,  705,
      466,  505,  486,  503,    0,    0,    0,    0,  490,  491,
      496,  481,  495,  487,    0,  485,  474,  465,  464,  464,
      463,  462,    0,  459,  446,  445,  460,  458,  458,  455,
      441,  444,  452,    0,  451,  434,    0,  444,  434,  432,
      440,  439,    0,    0,  440,    0,  423,  415,  414,    0,
      414,  413,  396,  414,    0,  414,  415,    0,    0,  406,
      389,  374,  386,  371,  366,    0,    0,  355,    0,    0,
        0,  352,    0,  343,    0,  266,  344,  317,    0,  329,
        0,    0,    0,    0,  319,  326,  327,  310,    0,    0,

        0,  315,  294,  289,  291,  291,  285,  286,  279,    0,
        0,  255,  245,  247,  235,  225,    0,    0,    0,  214,
      198,  181,    0,  180,  137,    0,  128,    0,  100,    0,
      110,    0,    0,  705,   95,    0,   38,    0,  705,  511,
      516,  519,  521,  526,  531,   68
    } ;

static const flex_int16_t yy_def[447] =
    {   0,
      439,    1,  439,  439,  439,  439,  439,  439,  440,  439,
      439,  441,  439,  439,  439,  439,  439,  439,  439,  439,
      442,  442,  439,  439,  439,  439,  439,  439,  439,  443,
      439,  439,  439,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  439,  439,  439,  439,  439,  440,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  444,  445,  439,  439,  442,   78,  442,
      442,  442,  442,  442,  442,  439,   78,  442,  442,  439,
      439,  439,  439,  439,  439,  439,  443,  439,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  439,  439,  439,
      439,  439,  439,  439,  439,  444,  444,  445,  439,  439,
      439,  439,   78,   89,  439,  439,  439,  446,   85,  439,
       78,  439,  439,  439,  439,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  439,  439,  444,  439,  439,  442,  439,
      439,  439,  439,  446,  169,  439,  442,  439,  439,  439,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  439,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  439,  439,  439,
      442,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  439,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  439,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  443,  439,  443,  443,

      443,  443,  443,  443,  443,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  439,  443,  443,  443,  443,  443,
      443,  443,  443,  443,  443,  443,  439,  443,  443,  443,
      443,  443,  443,  439,  443,  443,  443,  443,    0,  439,
      439,  439,  439,  439,  439,  439
    } ;

static const flex_int16_t yy_nxt[775] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   22,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   30,
       30,   30,   30,   30,   30,   30,   31,   32,   33,   30,
       34,   35,   36,   37,   38,   39,   40,   30,   41,   30,
       42,   43,   44,   45,   46,   30,   47,   48,   49,   50,
       51,   52,   30,   53,   30,   54,   55,   56,   57,   62,
       67,  244,   72,   69,   73,   73,   73,   73,   95,   96,
       74,  438,   68,   70,   71,   75,   63,   91,   92,   93,
       99,  108,  101,   76,   77,  102,   78,   78,   78,   79,

      109,  272,  103,  143,  273,  104,  100,  110,   81,  111,
       82,   83,  105,   84,   85,  106,  144,  113,  107,  112,
       81,  217,  139,   82,   83,  114,  118,  115,  140,   84,
      116,  141,  119,  120,  123,  148,  128,  218,  124,  437,
      129,   85,   86,   86,  145,  146,   77,  125,   87,   87,
       87,   87,  130,  126,  436,  131,   79,   79,   79,  174,
      175,  209,   82,   83,  435,   88,  210,   86,   86,  133,
       89,  434,  134,  181,  182,   82,   83,  149,   80,  198,
      199,   88,  433,  135,  136,  229,  137,  230,  138,   73,
       73,   73,   73,  159,  159,  159,  159,  170,  170,  170,

      170,  190,  153,  154,  155,  191,  160,  161,  162,   77,
      222,  163,  163,  163,   79,  153,  154,  155,  223,  160,
      161,  162,  285,  157,  286,   82,   83,  439,  236,  439,
      439,  439,  439,  164,  212,  260,  261,  432,   82,   83,
      439,  431,  165,  165,  439,  439,  166,  213,  166,  439,
      214,  167,  167,  167,  167,  439,  430,  439,  439,  439,
      439,  439,  429,  439,  439,  439,  439,  439,  428,  168,
      168,  168,  168,  439,  239,  439,  439,  439,  439,  427,
      169,  169,  169,  169,  169,  171,  171,  171,  171,  224,
      239,  426,  169,  169,  169,  169,  169,  169,  425,  241,

      241,  439,   88,  172,  172,  172,  172,   89,  225,  234,
      407,  234,  226,  424,  235,  235,  235,  235,   88,  310,
       88,  241,  311,  423,  408,   89,  159,  159,  159,  159,
      167,  167,  167,  167,  422,  310,   88,  421,  311,  160,
      161,  162,  237,  420,  237,  419,  418,  238,  238,  238,
      238,  417,  160,  161,  162,  240,  240,  240,  439,  416,
      415,  167,  167,  167,  167,  170,  170,  170,  170,  414,
      413,  412,  239,  411,  242,  410,  243,  164,  171,  171,
      171,  171,  246,  235,  235,  235,  235,  242,  239,  243,
      244,  244,  244,  244,  409,  247,  406,  405,  246,  404,

       89,  245,  245,  245,  245,  245,  172,  172,  172,  172,
      403,  247,  245,  245,  245,  245,  245,  245,  245,  235,
      235,  235,  235,  248,  238,  238,  238,  238,  249,  402,
      401,  400,  153,  399,  155,  238,  238,  238,  238,  248,
      240,  240,  240,  241,  241,  153,  398,  155,  160,  439,
      162,  439,  439,  439,  439,  397,  396,  308,  395,  394,
      309,  160,  240,  162,  439,  241,  439,  439,  439,  439,
      393,  392,  391,  308,  390,  389,  309,  172,  172,  172,
      172,  439,  388,  439,  439,  439,  439,  387,  386,  385,
      384,  383,  382,  381,  248,  380,  379,  378,  377,  249,

      376,  375,  374,  373,  372,  371,  370,  369,  368,  367,
      248,   59,   59,   59,   59,   59,   64,  366,   64,   64,
       64,   80,   80,   80,   97,   97,  156,  156,  156,  156,
      156,  158,  365,  158,  158,  158,  364,  363,  362,  361,
      360,  359,  358,  357,  356,  355,  354,  353,  352,  351,
      350,  349,  348,  347,  346,  345,  344,  343,  342,  341,
      340,  339,  338,  337,  336,  335,  334,  333,  332,  331,
      330,  329,  328,  327,  326,  325,  324,  301,  323,  322,
      321,  320,  319,  318,  317,  316,  315,  314,  313,  312,
      157,  307,  306,  305,  304,  303,  302,  301,  300,  299,

      298,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  259,  258,  257,  256,  255,  254,  253,
      252,  251,  250,  157,  233,  232,  231,  228,  227,  221,
      220,  219,  216,  215,  211,  208,  207,  206,  205,  204,
      203,  202,  201,  200,  197,  196,  195,  194,  193,  192,
      189,  188,  187,  186,  185,  184,  183,  180,  179,  178,
      177,  176,  173,  157,  152,  151,  150,   60,  147,  142,
      132,  127,  122,  121,  117,   98,   94,   90,   66,   65,

       61,   60,   58,  439,    3,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439
    } ;

static const flex_int16_t yy_chk[775] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   11,
       16,  446,   19,   18,   19,   19,   19,   19,   27,   27,
       20,  437,   16,   18,   18,   20,   11,   25,   25,   25,
       34,   37,   35,   20,   21,   35,   21,   21,   21,   21,

       37,  197,   35,   51,  197,   36,   34,   38,   21,   38,
       21,   21,   36,   21,   21,   36,   51,   39,   36,   38,
       21,  135,   49,   21,   21,   39,   41,   39,   49,   21,
       39,   49,   41,   41,   44,   55,   46,  135,   44,  435,
       46,   21,   22,   22,   52,   52,   22,   44,   22,   22,
       22,   22,   46,   44,  431,   46,   79,   79,   79,   96,
       96,  130,   22,   22,  429,   22,  130,   22,   22,   48,
       22,  427,   48,  104,  104,   22,   22,   55,   79,  120,
      120,   22,  425,   48,   48,  144,   48,  144,   48,   73,
       73,   73,   73,   77,   77,   77,   77,   86,   86,   86,

       86,  112,   73,   73,   73,  112,   77,   77,   77,   78,
      139,   78,   78,   78,   78,   73,   73,   73,  139,   77,
       77,   77,  210,  157,  210,   78,   78,   80,  157,   80,
       80,   80,   80,   78,  132,  185,  185,  424,   78,   78,
       81,  422,   81,   81,   81,   81,   82,  132,   82,   82,
      132,   82,   82,   82,   82,   83,  421,   83,   83,   83,
       83,   84,  420,   84,   84,   84,   84,   85,  416,   85,
       85,   85,   85,   88,  163,   88,   88,   88,   88,  415,
       85,   85,   85,   85,   85,   87,   87,   87,   87,  141,
      163,  414,   85,   85,   85,   85,   85,   85,  413,  165,

      165,   89,   87,   89,   89,   89,   89,   87,  141,  154,
      386,  154,  141,  412,  154,  154,  154,  154,   87,  244,
       89,  165,  245,  409,  386,   89,  159,  159,  159,  159,
      166,  166,  166,  166,  408,  244,   89,  407,  245,  159,
      159,  159,  161,  406,  161,  405,  404,  161,  161,  161,
      161,  403,  159,  159,  159,  164,  164,  164,  164,  402,
      398,  167,  167,  167,  167,  170,  170,  170,  170,  397,
      396,  395,  164,  390,  167,  388,  167,  164,  171,  171,
      171,  171,  170,  234,  234,  234,  234,  167,  164,  167,
      169,  169,  169,  169,  387,  171,  384,  382,  170,  378,

      171,  169,  169,  169,  169,  169,  172,  172,  172,  172,
      375,  171,  169,  169,  169,  169,  169,  169,  169,  235,
      235,  235,  235,  172,  237,  237,  237,  237,  172,  374,
      373,  372,  235,  371,  235,  238,  238,  238,  238,  172,
      240,  240,  240,  241,  241,  235,  370,  235,  238,  239,
      238,  239,  239,  239,  239,  367,  366,  240,  364,  363,
      241,  238,  240,  238,  247,  241,  247,  247,  247,  247,
      362,  361,  359,  240,  358,  357,  241,  249,  249,  249,
      249,  311,  355,  311,  311,  311,  311,  352,  351,  350,
      349,  348,  346,  345,  249,  343,  342,  341,  340,  249,

      339,  338,  337,  336,  335,  334,  332,  331,  330,  329,
      249,  440,  440,  440,  440,  440,  441,  328,  441,  441,
      441,  442,  442,  442,  443,  443,  444,  444,  444,  444,
      444,  445,  327,  445,  445,  445,  326,  324,  323,  322,
      321,  320,  319,  314,  313,  312,  307,  305,  304,  300,
      299,  297,  296,  295,  294,  293,  292,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  279,  278,
      277,  275,  274,  273,  272,  270,  269,  268,  267,  266,
      263,  262,  261,  260,  259,  257,  254,  253,  252,  251,
      236,  233,  232,  231,  230,  229,  227,  225,  224,  223,

      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  209,  208,  207,  206,  205,  204,  202,  201,
      200,  199,  198,  196,  194,  193,  192,  191,  190,  189,
      188,  187,  186,  184,  183,  182,  181,  180,  179,  178,
      177,  176,  175,  156,  147,  146,  145,  143,  142,  138,
      137,  136,  134,  133,  131,  129,  128,  127,  126,  125,
      124,  123,  122,  121,  119,  117,  116,  115,  114,  113,
      111,  110,  109,  108,  107,  106,  105,  103,  102,  101,
      100,   99,   91,   74,   72,   65,   64,   59,   53,   50,
       47,   45,   43,   42,   40,   33,   26,   23,   15,   12,

       10,    9,    8,    3,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439,  439,  439,  439,  439,  439,  439,
      439,  439,  439,  439
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[141] =
    {   0,
0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "new_lex.l"
#line 2 "new_lex.l"
    #include<bits/stdc++.h>
    using namespace std;
    #include "ast.h"
    #include "symtab.h"
    #include "new.tab.h"
    extern YYSTYPE yylval;
    int yylex();

    int flag =0;
#line 799 "lex.yy.c"
#line 800 "lex.yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 19 "new_lex.l"


#line 1020 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 440 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 705 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 21 "new_lex.l"
{
    //printf(" ");
}
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 25 "new_lex.l"
{
    //printf("\n");
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 29 "new_lex.l"
{
    //printf("\t");
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 33 "new_lex.l"
{
    // //printf("//comment ");
}
	YY_BREAK
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 36 "new_lex.l"
{
    // Handling Comment
    //printf("/*Comment*/");
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "new_lex.l"
{
    //printf("=");
    yylval.str = yytext;
    return ASN;
}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "new_lex.l"
{
    //printf("*=");
    yylval.str = yytext;
    return MUASN;
}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 51 "new_lex.l"
{
    //printf("/=");
    yylval.str = yytext;
    return DIASN;
}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "new_lex.l"
{
    //printf("mod=");
    yylval.str = yytext;
    return MODASN;
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 61 "new_lex.l"
{
    //printf("+=");
    yylval.str = yytext;
    return PLASN;
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 66 "new_lex.l"
{
    //printf("-=");
    yylval.str = yytext;
    return MIASN;
}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 71 "new_lex.l"
{
    //printf("<<=");
    yylval.str = yytext;
    return SLASN;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 76 "new_lex.l"
{
    //printf(">>=");
    yylval.str = yytext;
    return SRASN;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 81 "new_lex.l"
{
    //printf(">>>=");
    yylval.str = yytext;
    return LSRASN;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 86 "new_lex.l"
{
    
    //printf("&=");
    yylval.str = yytext;
    return ANDASN;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 92 "new_lex.l"
{
    //printf("^=");
    yylval.str = yytext;
    return CARETASN;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 97 "new_lex.l"
{
    //printf("|=");
    yylval.str = yytext;
    return ORASN;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 103 "new_lex.l"
{
    //printf("(");
    yylval.str = yytext;
    return LP;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 108 "new_lex.l"
{
    //printf(")");
    yylval.str = yytext;
    return RP;
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 113 "new_lex.l"
{
    //printf("{");
    yylval.str = yytext;

    // if(flag==0){
    //     addChild();
    // }
    // else{
    //     flag=0;
    // }

    return LC;
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 126 "new_lex.l"
{
    //printf("}");
    yylval.str = yytext;

    // goUp();

    return RC;
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 134 "new_lex.l"
{
    //printf("[");
    yylval.str = yytext;
    return LB;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 139 "new_lex.l"
{
    //printf("]");
    yylval.str = yytext;
    return RB;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 144 "new_lex.l"
{
    //printf("<");
    yylval.str = yytext;
    return LT;
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 149 "new_lex.l"
{
    //printf(">");
    yylval.str = yytext;
    return GT;
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 154 "new_lex.l"
{
    //printf(";");
    yylval.str = yytext;
    return SM;
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 159 "new_lex.l"
{
    //printf(",");
    yylval.str = yytext;
    return CM;
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 164 "new_lex.l"
{
    //printf(".");
    yylval.str = yytext;
    return DOT;
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 169 "new_lex.l"
{
    //printf("!");
    yylval.str = yytext;
    return EXCL;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 174 "new_lex.l"
{
    //printf("~");
    yylval.str = yytext;
    return TILDE;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 179 "new_lex.l"
{
    //printf("^");
    yylval.str = yytext;
    return CARET;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 184 "new_lex.l"
{
    //printf("?");
    yylval.str = yytext;
    return QUEST;
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 189 "new_lex.l"
{
    //printf(":");
    yylval.str = yytext;
    return COLON;
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 194 "new_lex.l"
{
    //printf("::");
    yylval.str = yytext;
    return ACCESSSPEC;
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 200 "new_lex.l"
{
    //printf("++");
    yylval.str = yytext;
    return INC;
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 205 "new_lex.l"
{
    //printf("--");
    yylval.str = yytext;
    return DEC;
}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 211 "new_lex.l"
{
    //printf("+");
    yylval.str = yytext;
    return PLUS;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 216 "new_lex.l"
{
    //printf("-");
    yylval.str = yytext;
    return MINUS;
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 221 "new_lex.l"
{
    //printf("*");
    yylval.str = yytext;
    return MUL;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 226 "new_lex.l"
{
    //printf("/");
    yylval.str = yytext;
    return DIV;
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 231 "new_lex.l"
{
    //printf("mod");
    yylval.str = yytext;
    return MOD;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 237 "new_lex.l"
{
    //printf("<<");
    yylval.str = yytext;
    return SHL;
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 242 "new_lex.l"
{
    //printf("<<");
    yylval.str = yytext;
    return SHR;
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 247 "new_lex.l"
{
    //printf(">>>");
    yylval.str = yytext;
    return LSHR;
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 253 "new_lex.l"
{
    //printf("<=");
    yylval.str = yytext;
    return LE;
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 258 "new_lex.l"
{
    //printf(">=");
    yylval.str = yytext;
    return GE;
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 263 "new_lex.l"
{
    //printf("==");
    yylval.str = yytext;
    return EQ;
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 268 "new_lex.l"
{
    //printf("!=");
    yylval.str = yytext;
    return NE;
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 274 "new_lex.l"
{
    //printf("&");
    yylval.str = yytext;
    return AND;
}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 279 "new_lex.l"
{
    //printf("|");
    yylval.str = yytext;
    return OR;
}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 284 "new_lex.l"
{
    //printf("&&");
    yylval.str = yytext;
    return ANDAND;
}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 289 "new_lex.l"
{
    //printf("||");
    yylval.str = yytext;
    return OROR;
}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 295 "new_lex.l"
{
    //printf("->");
    yylval.str = yytext;
    return ARROW;
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 300 "new_lex.l"
{
    //printf("<>");
    yylval.str = yytext;
    return DIAMOND;
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 305 "new_lex.l"
{
    //printf("@");
    yylval.str = yytext;
    return ATR;
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 310 "new_lex.l"
{
    //printf("...");
    yylval.str = yytext;
    return TDOT;
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 316 "new_lex.l"
{
    //printf("var");
    yylval.str = yytext;
    return VAR;
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 321 "new_lex.l"
{
    //printf("new");
    yylval.str = yytext;
    return NEW;
}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 326 "new_lex.l"
{
    //printf("super");
    yylval.str = yytext;
    return SUPER;
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 331 "new_lex.l"
{
    //printf("class");
    yylval.str = yytext;
    return CLASS;
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 336 "new_lex.l"
{
    //printf("void");
    yylval.str = yytext;
    return VOID;
}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 341 "new_lex.l"
{
    //printf("this");
    yylval.str = yytext;
    return THIS;
}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 346 "new_lex.l"
{
    //printf("try");
    yylval.str = yytext;
    return TRY;
}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 352 "new_lex.l"
{
    //printf("instanceof");
    yylval.str = yytext;
    return INSTANCEOF;
}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 357 "new_lex.l"
{
    //printf("finally");
    yylval.str = yytext;
    return FINALLY;
}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 362 "new_lex.l"
{
    //printf("finally");
    yylval.str = yytext;

    flag=1;
    // addChild();

    return CATCH;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 371 "new_lex.l"
{
    //printf("synchronized");
    yylval.str = yytext;
    return SYNCHRONIZED;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 376 "new_lex.l"
{
    //printf("throw");
    yylval.str = yytext;
    return THROW;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 381 "new_lex.l"
{
    //printf("return");
    yylval.str = yytext;
    return RETURN;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 386 "new_lex.l"
{
    //printf("continue");
    yylval.str = yytext;
    return CONTINUE;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 391 "new_lex.l"
{
    //printf("yield");
    yylval.str = yytext;
    return YIELD;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 396 "new_lex.l"
{
    //printf("break");
    yylval.str = yytext;
    return BREAK;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 402 "new_lex.l"
{
    //printf("for");
    yylval.str = yytext;

    flag=1;
    // addChild();

    return FOR;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 411 "new_lex.l"
{
    //printf("do");
    yylval.str = yytext;
    return DO;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 416 "new_lex.l"
{
    //printf("while");
    yylval.str = yytext;
    return WHILE;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 421 "new_lex.l"
{
    //printf("default");
    yylval.str = yytext;
    return DEFAULT;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 426 "new_lex.l"
{
    //printf("assert");
    yylval.str = yytext;
    return ASSERT;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 431 "new_lex.l"
{
    //printf("switch");
    yylval.str = yytext;
    return SWITCH;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 436 "new_lex.l"
{
    //printf("case");
    yylval.str = yytext;
    return CASE;
}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 441 "new_lex.l"
{
    //printf("if");
    yylval.str = yytext;
    return IF;
}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 446 "new_lex.l"
{
    //printf("else");
    yylval.str = yytext;
    return ELSE;
}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 452 "new_lex.l"
{
    //printf("byte");
    yylval.str = yytext;
    return BYTE;
}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 457 "new_lex.l"
{
    //printf("boolean");
    yylval.str = yytext;
    return BOOLEAN;
}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 462 "new_lex.l"
{
    //printf("char");
    yylval.str = yytext;
    return CHAR;
}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 467 "new_lex.l"
{
    //printf("double");
    yylval.str = yytext;
    return DOUBLE;
}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 472 "new_lex.l"
{
    //printf("float");
    yylval.str = yytext;
    return FLOAT;
}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 477 "new_lex.l"
{
    //printf("int");
    yylval.str = yytext;
    return INT;
}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 482 "new_lex.l"
{
    //printf("long");
    yylval.str = yytext;
    return LONG;
}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 487 "new_lex.l"
{
    //printf("short");
    yylval.str = yytext;
    return SHORT;
}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 493 "new_lex.l"
{
    //printf("const");
    yylval.str = yytext;
    return CONST;
}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 498 "new_lex.l"
{
    //printf("goto");
    yylval.str = yytext;
    return GOTO;
}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 504 "new_lex.l"
{
    //printf("abstract");
    yylval.str = yytext;
    return ABSTRACT;
}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 509 "new_lex.l"
{
    //printf("protected");
    yylval.str = yytext;
    return PROTECTED;
}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 514 "new_lex.l"
{
    //printf("public");
    yylval.str = yytext;
    return PUBLIC;
}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 519 "new_lex.l"
{
    //printf("private");
    yylval.str = yytext;
    return PRIVATE;
}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 524 "new_lex.l"
{
    //printf("interface");
    yylval.str = yytext;
    return INTERFACE;
}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 529 "new_lex.l"
{
    //printf("static");
    yylval.str = yytext;
    return STATIC;
}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 534 "new_lex.l"
{
    //printf("strictfp");
    yylval.str = yytext;
    return STRICTFP;
}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 539 "new_lex.l"
{
    //printf("final");
    yylval.str = yytext;
    return FINAL;
}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 544 "new_lex.l"
{
    //printf("permits");
    yylval.str = yytext;
    return PERMITS;
}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 549 "new_lex.l"
{
    //printf("permits");
    yylval.str = yytext;
    return EXTENDS;
}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 554 "new_lex.l"
{
    //printf("sealed");
    yylval.str = yytext;
    return SEALED;
}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 559 "new_lex.l"
{
    //printf("non-sealed");
    yylval.str = yytext;
    return NSEALED;
}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 564 "new_lex.l"
{
    //printf("transitive");
    yylval.str = yytext;
    return TRANSITIVE;
}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 569 "new_lex.l"
{
    //printf("transitive");
    yylval.str = yytext;
    return THROWS;
}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 574 "new_lex.l"
{
    //printf("native");
    yylval.str = yytext;
    return NATIVE;
}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 579 "new_lex.l"
{
    //printf("transient");
    yylval.str = yytext;
    return TRANSIENT;
}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 584 "new_lex.l"
{
    //printf("volatile");
    yylval.str = yytext;
    return VOLATILE;
}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 589 "new_lex.l"
{
    //printf("implements");
    yylval.str = yytext;
    return IMPLEMENTS;
}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 595 "new_lex.l"
{
    //printf("provides");
    yylval.str = yytext;
    return PROVIDES;
}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 601 "new_lex.l"
{
    //printf("with");
    yylval.str = yytext;
    return WITH;
}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 607 "new_lex.l"
{
    //printf("uses");
    yylval.str = yytext;
    return USES;
}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 613 "new_lex.l"
{
    //printf("opens");
    yylval.str = yytext;
    return OPENS;
}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 619 "new_lex.l"
{
    //printf("record");
    yylval.str = yytext;
    return RECORD;
}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 624 "new_lex.l"
{
    //printf("to");
    yylval.str = yytext;
    return TO;
}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 629 "new_lex.l"
{
    //printf("exports");
    yylval.str = yytext;
    return EXPORTS;
}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 634 "new_lex.l"
{
    //printf("requires");
    yylval.str = yytext;
    return REQUIRES;
}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 639 "new_lex.l"
{
    //printf("open");
    yylval.str = yytext;
    return OPEN;
}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 644 "new_lex.l"
{
    //printf("module");
    yylval.str = yytext;
    return MODULE;
}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 649 "new_lex.l"
{
    //printf("import");
    yylval.str = yytext;
    return IMPORT;
}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 654 "new_lex.l"
{
    //printf("package");
    yylval.str = yytext;
    return PACKAGE;
}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 659 "new_lex.l"
{
    //printf("enum");
    yylval.str = yytext;
    return ENUM;
}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 666 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "INT", yylineno);
    return INTLITERAL;
}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 672 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "INT", yylineno);
    return INTLITERAL;
}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 678 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "INT", yylineno);
    return INTLITERAL;
}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 684 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "INT", yylineno);
    return INTLITERAL;
}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 691 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "FLOAT", yylineno);
    return FLOATLITERAL;
}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 697 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "FLOAT", yylineno);
    return FLOATLITERAL;
}
	YY_BREAK
case 129:
YY_RULE_SETUP
#line 703 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "FLOAT", yylineno);
    return FLOATLITERAL;
}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 709 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "FLOAT", yylineno);
    return FLOATLITERAL;
}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 715 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "FLOAT", yylineno);
    return FLOATLITERAL;
}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 721 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "FLOAT", yylineno);
    return FLOATLITERAL;
}
	YY_BREAK
case 133:
YY_RULE_SETUP
#line 727 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "FLOAT", yylineno);
    return FLOATLITERAL;
}
	YY_BREAK
case 134:
YY_RULE_SETUP
#line 734 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "BOOL", yylineno);
    return BOOLLITERAL;
}
	YY_BREAK
case 135:
/* rule 135 can match eol */
YY_RULE_SETUP
#line 741 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "STRING", yylineno);
    return STRINGLITERAL;
}
	YY_BREAK
case 136:
YY_RULE_SETUP
#line 748 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "CHAR", yylineno);
    return CHARLITERAL;
}
	YY_BREAK
case 137:
YY_RULE_SETUP
#line 755 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertLit(yytext, "NULL", yylineno);
    return NULLLITERAL;
}
	YY_BREAK
case 138:
YY_RULE_SETUP
#line 762 "new_lex.l"
{
    //printf("%s", yytext);
    yylval.str = yytext;
    // insertId(yytext, yylineno);
    return IDENT;
}
	YY_BREAK
case 139:
YY_RULE_SETUP
#line 769 "new_lex.l"
{
    //printf("Invalid Identifier at line number %d on the lexeme %s\n", yylineno, yytext);
    return 0;
}
	YY_BREAK
case 140:
YY_RULE_SETUP
#line 776 "new_lex.l"
ECHO;
	YY_BREAK
#line 2372 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 440 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 440 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 439);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 776 "new_lex.l"


int yywrap() {return 1;}

